### ISSUE TITLE
配置样例少了左括号

### ISSUE THREAD

**Issue by latavin243** [cabins/cabins.github.io#1]
https://github.com/cabins/cabins.github.io/blob/58fd0a65cd3795b5ecc16d3fe0c2aa8efa4d33a8/emacs/using-emacs-like-a-pro/index.html#L256

**Comment by cabins** [comment]
> https://github.com/cabins/cabins.github.io/blob/58fd0a65cd3795b5ecc16d3fe0c2aa8efa4d33a8/emacs/using-emacs-like-a-pro/index.html#L256

已修复。非常感谢！！
